#!/bin/bash

nvidia-smi --query-gpu=name,memory.total,memory.free --format=csv,noheader

pip install -qq git+https://github.com/ShivamShrirao/diffusers
pip install -q -U --pre triton
pip install -q accelerate==0.12.0 transformers ftfy bitsandbytes gradio natsort

#mkdir -p ~/.huggingface
#HUGGINGFACE_TOKEN = "" #@param {type:"string"}
#echo -n "{HUGGINGFACE_TOKEN}" > ~/.huggingface/token

pip install -q https://github.com/metrolobo/xformers_wheels/releases/download/1d31a3ac_various_6/xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl
# все установил в dreambooth